src/main/java/ru/demo/model/Card.java
package ru.demo.model;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Created by dmitri
 */
public class Card implements Comparable<Card> {
    private static SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
    private static SimpleDateFormat sdfView = new SimpleDateFormat("MMM-yyyy");

    private Logger logger = LoggerFactory.getLogger(getClass());

    private String bank;
    private String number;
    private Date expiryDate;

    public Card() {}

    public Card(String bank, String number, Date expiryDate) {
        this.bank = bank;
        this.number = number;
        this.expiryDate = expiryDate;
    }

    public String getBank() {
        return bank;
    }
    public void setBank(String bank) {
        this.bank = bank;
    }

    public String getNumber() {
        return number;
    }
    public void setNumber(String number) {
        this.number = number;
    }
    public String getNumberMasked() {
        String mask = new StringBuilder(number.substring(0,4))
                .append(number.substring(4).replaceAll("[^-]", "x")).toString();
        return mask;
    }

    public Date getExpiryDate() {
        return expiryDate;
    }
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }
    public void setExpiryDate(String input) throws ParseException {
        expiryDate = sdfView.parse(input);
    }

    /**
     * Comparing the Cards first by expiry date (descending), then bank name and card number.
     * @param o The other instance to compare to.
     * @return 1 if this is previous than o, 0 once they are equal, otherwise -1.
     */
    @Override
    public int compareTo(Card o) {
        int res = 0;

        if (this == o) {
            return res;
        }

        res = this.expiryDate.compareTo(o.expiryDate);
        if (res != 0) {
            return -1 * res;
        }

        res = this.bank.compareTo(o.bank);
        if (res != 0) {
            return res;
        }

        res = this.number.compareTo(o.number);
        return res;
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || !(o instanceof Card)) {
            return false;
        }

        return compareTo((Card)o) == 0;
    }

    @Override
    public int hashCode() {
        int result = bank.hashCode();
        result = 31 * result + number.hashCode();
        result = 31 * result + expiryDate.hashCode();
        return result;
    }

    @Override
    public String toString() {
        return "Card{" +
                "bank='" + bank + '\'' +
                ", number='" + number + '\'' +
                ", expiryDate=" + sdf.format(expiryDate) +
                "}";
    }
}

src/main/java/ru/demo/model/to/CardTO.java
package ru.demo.model.to;

/**
 * Created by dmitri
 */
public class CardTO {
public String bankName;
    public String cardNumber;
    public String expiryMonth;
    public int expiryYear;

    public String getBankName() {
        return bankName;
    }
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    public String getCardNumber() {
        return cardNumber;
    }
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    public String getExpiryMonth() {
        return expiryMonth;
    }
    public void setExpiryMonth(String expiryMonth) {
        this.expiryMonth = expiryMonth;
    }

    public int getExpiryYear() {
        return expiryYear;
    }
    public void setExpiryYear(int expiryYear) {
        this.expiryYear = expiryYear;
    }
}

src/main/java/ru/demo/controllers/MainController.java
package ru.demo.controllers;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.servlet.ModelAndView;
import ru.demo.managers.CardManager;
import ru.demo.model.Card;
import ru.demo.model.to.CardTO;
import ru.demo.services.InputDocumentParser;

import java.io.IOException;
import java.io.InputStream;
import java.util.*;
import java.util.concurrent.ConcurrentSkipListSet;

@Controller
@Scope(value = "session")
public class MainController {
    private Logger logger = LoggerFactory.getLogger(getClass());

    @Autowired
    CardManager cardManager;
    @Autowired
    InputDocumentParser parser;

    Set<Card> cards = new ConcurrentSkipListSet<>();

    @RequestMapping(value = "/", method = RequestMethod.GET)
    public ModelAndView list() {
        ModelAndView mav = new ModelAndView("main");
        mav.addObject("cards", cards);
        CardTO cardTO = new CardTO();
        mav.addObject("cardTO", cardTO);
        return mav;
    }

    @RequestMapping(value = "/addCardDetail", method = RequestMethod.POST)
    public String addCardDetail(@ModelAttribute("cardTO") CardTO details,
                                BindingResult bindingResult, Model model) {
        Card card = cardManager.createCard(details);

        ModelAndView mav = new ModelAndView();
        mav.addAllObjects(model.asMap());
        if (card == null) {
            model.addAttribute("error", "Cannot create the card with given details.");
        } else {
            cards.add(card);
        }

        return "redirect:/";
    }

    @RequestMapping(value = "/clearAll", method = RequestMethod.GET)
    public String clearAll(ModelMap model) {
        cards.clear();
        return "redirect:/";
    }

    @RequestMapping(value = "/uploadFile", method = RequestMethod.POST)
    public
    @ResponseBody
    String uploadFile(@RequestParam("file") MultipartFile file) {
        String fileName = file.getOriginalFilename();
        long fileSize = file.getSize();
        String fileContentType = file.getContentType();
        int indexOfType = fileContentType.indexOf("text");
        int indexOfDelim = fileContentType.indexOf("/");

        String res;

        if (file.isEmpty()) {
            logger.warn("Cannot upload file '{}' size of '{}B': it's empty.", fileName, fileSize);
            res = String.format("You file '%s' is empty. Try another one.", fileName);
        } else if (indexOfType == -1 || indexOfType > indexOfDelim) {
            logger.warn("Cannot upload file '{}' size of '{}B': incorrect content type '{}'.",
                    new Object[]{fileName, fileSize, fileContentType});
            res = String.format("You file '%s' must be of plain text type. Try another one.", fileName);
        } else {
            try {
                InputStream inputStream = file.getInputStream();
                List<Card> list = parser.parse(inputStream);
                int added = 0;
                for (Iterator<Card> iterator = list.iterator(); iterator.hasNext(); ) {
                    Card card = iterator.next();
                    if (!cards.contains(card)) {
                        cards.add(card);
                        added++;
                    }
                }
                res = String.format("Your file '%s' was uploaded successfully. Parsed '%s' records" + ", among which only '%s' were new/unique and added.",
                        fileName, list.size(), added);
                inputStream.close();
            } catch (IOException e) {
                logger.error(String.format("Cannot upload file '%s' size of '%sB'.", fileName, fileSize), e);
                res = "Cannot create the card record with the given details.";
            }
        }

        return res;
    }
}

src/main/webapp/WEB-INF/views/jsp/main.jsp
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bank card demo</title>

    <spring:url value="/resources/core/css/main.css" var="coreCss"/>
    <spring:url value="/resources/core/css/bootstrap.min.css" var="bootstrapCss"/>
    <spring:url value="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" var="jQueryUiCss"/>

    <spring:url value="/resources/core/js/jquery-2.1.4.min.js" var="jQueryJS"/>
    <spring:url value="/resources/core/js/jquery-ui.min.js" var="jQueryUiJS"/>
    <spring:url value="/resources/core/js/environment.js" var="environmentJS"/>
    <spring:url value="/resources/core/js/createDialogValidation.js" var="createDialogValidationJS"/>
    <spring:url value="/resources/core/js/createDialog.js" var="createDialogJS"/>
    <spring:url value="/resources/core/js/uploadDialog.js" var="uploadDialogJS"/>
    <spring:url value="/resources/core/js/main.js" var="mainJs"/>

    <link href="${bootstrapCss}" rel="stylesheet"/>
    <link href="${coreCss}" rel="stylesheet"/>
    <link href="${jQueryUiCss}" rel="stylesheet"/>

    <script src="${jQueryJS}"></script>
    <script src="${jQueryUiJS}"></script>
    <script src="${environmentJS}"></script>
    <script src="${createDialogValidationJS}"></script>
    <script src="${createDialogJS}"></script>
    <script src="${uploadDialogJS}"></script>
    <script src="${mainJs}"></script>
</head>

<div class="header">
    <h3>Bank details</h3></p>
</div>

<hr>
<div class="container">
    <button class="popup-link-1" id="create-card-detail-open">Add new card detail</button>
    <button class="popup-link-2" id="upload-file-open">Upload file</button>
    <button class="popup-link-3" id="clear-all" href="<spring:url value="/clearAll"/>">Clear all cards</button>

    <c:if test="${not empty error}">
        <p class="error-msg">${error}</p>
    </c:if>

    <table style="width: 100%">
        <tr class="width-full">
            <th>Bank</th>
            <th>BankCard number</th>
            <th>Expiry date</th>
        </tr>

        <c:choose>
            <c:when test="${empty cards}">
                <tr class="width-full">
                    <td colspan="3">
                        <p>There is no one card detail by now.</p>
                    </td>
                </tr>
            </c:when>
            <c:otherwise>
                <c:forEach var="card" items="${cards}">
                    <tr>
                        <td>${card.bank}</td>
                        <td>${card.numberMasked}</td>
                        <td>
                            <fmt:formatDate value="${card.expiryDate}" var="formattedDate" type="date"
                                            pattern="MMM-yyyy"/>
                                ${formattedDate}
                        </td>
                    </tr>
                </c:forEach>
            </c:otherwise>
        </c:choose>
    </table>

    <div id="dialog-form" title="Adding new card detail" class="dialog hidden">
        <p class="validateTips">All form fields are required.</p>

        <spring:url value="/addCardDetail" var="createURL"/>
        <form:form id="createNewCardDetail" action="${createURL}" modelAttribute="cardTO" method="post">
            <fieldset>
                <table class="table width-full">
                    <tr>
                        <td nowrap="nowrap">
                            <form:label path="bankName">Bank name</form:label>
                        </td>
                        <td>
                            <form:input type="text" id="bankName" path="bankName" name="bankName"
                                        placeholder="Bank name"
                                        class="text ui-widget-content ui-corner-all width-full"/>
                        </td>
                    </tr>
                    <tr>
                        <td nowrap="nowrap">
                            <form:label path="cardNumber">Card number</form:label>
                        </td>
                        <td>
                            <form:input type="text" id="cardNumber" path="cardNumber" name="cardNumber"
                                        placeholder="xxxx-xxxx-xxxx-xxxx"
                                        class="text ui-widget-content ui-corner-all width-full"/>
                        </td>
                    </tr>
                    <tr>
                        <td class="vertical-align-top" nowrap="nowrap">
                            <label>Expiry date</label>
                        </td>
                        <td>
                            <table class="width-full">
                                <tr>
                                    <td>
                                        <form:label path="expiryMonth">month</form:label>
                                    </td>
                                    <td>
                                        <form:input id="expiryMonth" path="expiryMonth" name="expiryMonth"
                                                    list="monthList"
                                                    placeholder="Choose any" class="width-full"/>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <form:label path="expiryYear">year</form:label>
                                    </td>
                                    <td>
                                        <form:input type="number" id="expiryYear" path="expiryYear" name="expiryYear"
                                                    value="2015" width="50px" class="width-full"/>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
                <br/>
                <datalist id="monthList">
                    <option value="Jan">January</option>
                    <option value="Feb">February</option>
                    <option value="Mar">March</option>
                    <option value="Apr">April</option>
                    <option value="May">May</option>
                    <option value="Jun">June</option>
                    <option value="Jul">July</option>
                    <option value="Aug">August</option>
                    <option value="Sep">September</option>
                    <option value="Oct">October</option>
                    <option value="Nov">November</option>
                    <option value="Dec">December</option>
                </datalist>

                <input type="submit" tabindex="-1" style="position:absolute; top:-1000px">
            </fieldset>
        </form:form>
    </div>

    <div id="upload-file-container" title="Uploading CSV card details file" class="dialog hidden">
        <form id="upload-form" enctype="multipart/form-data">
            <input type="file" name="file" required/>
        </form>
        <progress class="width-full"></progress>
    </div>

    <hr>
</div>

</body>
</html>